# Generated by Django 5.1.7 on 2025-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='password',
            field=models.CharField(default='changeme', max_length=128),
        ),
    ]
