# Generated by Django 5.1.7 on 2025-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='security_answer1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='security_answer2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='security_question1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='security_question2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
