# Generated by Django 5.1.7 on 2025-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_name_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
