# Generated by Django 5.1.7 on 2025-06-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
    ]
