# Generated by Django 5.1.7 on 2025-06-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_order_user_id'),
    ]

    operations = [
    ]
