# Generated by Django 5.1.7 on 2025-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_clean_migration_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
