# Generated by Django 5.1.7 on 2025-06-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_shopuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('successful', 'Successful'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
