# Generated by Django 5.1.7 on 2025-06-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0002_order_name_order_payment_method'),
    ]

    operations = [
    ]
