# Generated by Django 5.1.7 on 2025-06-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0003_order_is_paid'),
        ('managepayments', '0003_remove_is_paid_field'),
    ]

    operations = [
    ]
