# Generated by Django 5.1.7 on 2025-06-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0004_merge_0003_order_is_paid_0003_remove_is_paid_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
