# Generated by Django 5.1.7 on 2025-06-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0005_remove_order_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.CharField(max_length=10)),
                ('classroom', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=20)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='managepayments.order')),
            ],
        ),
    ]
