# Generated by Django 5.1.7 on 2025-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0006_deliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
