# Generated by Django 5.1.7 on 2025-06-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0007_orderitem_is_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryInfo',
        ),
    ]
