# Generated by Django 5.1.7 on 2025-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0009_deliveryinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryinfo',
            options={'verbose_name': 'Delivery info', 'verbose_name_plural': 'Delivery info'},
        ),
    ]
