# Generated by Django 5.1.7 on 2025-06-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managepayments', '0010_alter_deliveryinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_successful', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('delivery_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='managepayments.deliveryinfo')),
            ],
            options={
                'verbose_name': 'Delivery status',
                'verbose_name_plural': 'Delivery status',
            },
        ),
    ]
